creación del crud de identification type
LuisHoyos7/inventy-api pull request #25
Opened 2024-09-12 16:43 UTC by RRohatan

se agregaron los campos en la migración de identication type, el repositorio de restify y el modelo con sus relaciones

2024-09-12 17:38 UTC, DeiverJC requested changes

2024-09-12 17:38 UTC, DeiverJC commented on app/Models/IdentificationType.php
> +
agregar `name` y `code` al array de `$fillables`

2024-09-12 17:38 UTC, DeiverJC commented on app/Models/IdentificationType.php
> +    public function companies()
eliminar la relacion con company

2024-09-12 17:38 UTC, DeiverJC commented on app/Restify/IdentificationTypeRepository.php
> +<?php
eliminar este archivo

2024-09-12 19:21 UTC, RRohatan commented
se realizan las correcciones solicitadas

2024-09-13 11:01 UTC, DeiverJC commented on app/Models/IdentificationType.php
> +
@RRohatan aun te falta este cambio, en el modelo tienes que agragar la propiedad `$fillable` con los campos `name` & `code`

**Doc ref:** https://laravel.com/docs/11.x/eloquent#mass-assignment

2024-09-13 14:21 UTC, RRohatan commented on app/Models/IdentificationType.php
> +
se agregan los campos fillable del modelo

2024-09-13 22:44 UTC, merged